on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install root dependencies
        run: bun install

      - name: Execute nuke-build.ps1
        run: ./scripts/nuke-build.ps1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MicroBanking-Windows-Installer
          path: |
            desktop/target/release/bundle/msi/*.msi
            desktop/target/release/bundle/nsis/*.exe
